# Generated by Django 6.0.5 on 2026-05-23 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mijoz_ismi', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('manzil', models.TextField()),
                ('holat', models.CharField(choices=[('yangi', 'Yangi'), ('jarayonda', 'Jarayonda'), ('yetkazildi', 'Yetkazildi'), ('bekor', 'Bekor qilindi')], default='yangi', max_length=20)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-yaratilgan'],
            },
        ),
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('emoji', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='', verbose_name='Аватарка: ')),
                ('name', models.CharField(max_length=200, verbose_name='Имя: ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена: ')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('tavsif', models.TextField(blank=True)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eski_narx', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rasm', models.ImageField(blank=True, upload_to='mahsulotlar/')),
                ('reyting', models.PositiveSmallIntegerField(default=5)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='main.kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-yaratilgan'],
            },
        ),
        migrations.CreateModel(
            name='BuyurtmaQatori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(default=1)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qatorlar', to='main.buyurtma')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mahsulot')),
            ],
        ),
    ]
