# Generated by Django 6.0.5 on 2026-05-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avatar',
            field=models.ImageField(upload_to='avatars/', verbose_name='Аватарка'),
        ),
    ]
